# Generated by Django 3.0.7 on 2020-06-22 22:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coding_arena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('dateTimeCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_arena.Gamer')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('A', 'A'), ('R', 'R'), ('P', 'P')], max_length=2)),
                ('challengeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_arena.Challenge')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_arena.Gamer')),
            ],
        ),
    ]
